"""
Per-project persona resolver.

Personas are plain markdown files that describe a role's mission + operating
style. They live with the project (a project `personas/` dir) so each project
owns its team. We also fall back to the harness's own `personas/` library.

Resolution order (first match wins by id):
  1. $CEO_PERSONAS_DIR (colon-separated list of dirs)
  2. <workspace>/personas        (the active project's data dir)
  3. <HARNESS_HOME>/personas      (the shipped harness library)

This is the single seam the A2A adapter + meeting orchestrator use to turn a
persona id (e.g. "architect") into the text injected ahead of an agent's task.
stdlib-only by design.
"""

from __future__ import annotations

import os
from pathlib import Path

from config import paths


def _candidate_dirs() -> list[Path]:
    dirs: list[Path] = []
    env = os.environ.get("CEO_PERSONAS_DIR", "")
    for chunk in env.split(os.pathsep):
        if chunk.strip():
            dirs.append(Path(chunk).expanduser())
    dirs.append(paths.workspace() / "personas")
    dirs.append(paths.workspace() / "runtime" / "harness" / "personas")
    dirs.append(paths.HARNESS_HOME / "personas")
    # de-dup, preserve order
    seen, out = set(), []
    for d in dirs:
        rd = d.resolve()
        if rd not in seen:
            seen.add(rd)
            out.append(d)
    return out


def _walk_md(root: Path):
    if not root.exists():
        return
    for p in root.rglob("*.md"):
        if p.is_file():
            yield p


def list_personas() -> list[dict]:
    """All discoverable personas as {id, name, path, source}. First id wins."""
    found: dict[str, dict] = {}
    for d in _candidate_dirs():
        for p in _walk_md(d):
            pid = p.stem
            if pid.lower() in {"readme", "index"}:
                continue
            key = pid.lower()
            if key not in found:
                found[key] = {
                    "id": pid,
                    "name": pid.replace("-", " ").replace("_", " ").title(),
                    "path": str(p),
                    "source": str(d),
                }
    return sorted(found.values(), key=lambda x: x["id"].lower())


def resolve(persona_id: str | None) -> dict | None:
    """Return {id, name, path, text} for a persona id, or None if not found."""
    if not persona_id:
        return None
    target = persona_id.strip().lower()
    for d in _candidate_dirs():
        for p in _walk_md(d):
            if p.stem.lower() == target:
                try:
                    text = p.read_text(encoding="utf-8")
                except Exception:
                    text = ""
                return {"id": p.stem, "name": p.stem.replace("-", " ").title(),
                        "path": str(p), "text": text}
    return None


def persona_preamble(persona_id: str | None) -> str:
    """The text to prepend to an agent's task so it acts in-persona. Empty if none."""
    pr = resolve(persona_id)
    if not pr or not pr.get("text"):
        return ""
    return (f"You are operating as the **{pr['name']}** persona. "
            f"Stay in this role for your entire reply.\n\n"
            f"--- PERSONA BRIEF ---\n{pr['text'].strip()}\n--- END PERSONA BRIEF ---\n")


# ---------------------------------------------------------------------------
# Interactive-session seeding
#
# The programmatic path (agent_adapter.converse/dispatch) prepends
# persona_preamble() to the first task. But a *mounted* agent's INTERACTIVE
# provider session (the tmux "main" window a human types into) never sees that
# preamble — so it answers generically. We fix that by writing the persona
# brief as an always-on context file (AGENTS.md / CLAUDE.md) into the agent's
# per-(room,agent) workdir; cwd-aware CLIs (devin, claude) load it as always-on
# context, so the session is in-character from the very first message.
# ---------------------------------------------------------------------------

def agent_context_markdown(persona_id: str | None) -> str:
    """The always-on context body that keeps an interactive CLI in-persona.

    Empty string when the persona has no resolvable brief (caller should then
    skip writing a file). Built from persona_preamble() so there is a single
    source of truth for the role text.
    """
    preamble = persona_preamble(persona_id)
    if not preamble:
        return ""
    return (
        "# Agent Operating Context (auto-generated by launch-agent)\n\n"
        "You are a mounted persona agent in the CEO Studio harness. Operate "
        "fully in character as the persona below from your very first reply, "
        "including when a human types directly into this terminal. Do not break "
        "character or answer as a generic assistant.\n\n"
        f"{preamble}"
    )


def _agent_workdir(room: str, agent: str) -> Path:
    """Mirror agent_adapter._workdir() without importing the providers stack:
    per-(room,agent) data dir under the active workspace."""
    return paths.room_dir(room) / "agents" / agent


def seed_agent_context(room: str, agent: str, persona_id: str | None) -> str:
    """Write the persona brief as always-on context (AGENTS.md + CLAUDE.md) into
    the agent's per-(room,agent) workdir so a cwd-aware interactive CLI loads it.

    Returns the workdir path as a string (the dir is always created so the
    caller can cd into it). Writing is a no-op when there is no persona brief.
    """
    wd = _agent_workdir(room, agent)
    wd.mkdir(parents=True, exist_ok=True)
    body = agent_context_markdown(persona_id)
    if body:
        # AGENTS.md covers devin (Standard) + most CLIs; CLAUDE.md covers claude.
        (wd / "AGENTS.md").write_text(body, encoding="utf-8")
        (wd / "CLAUDE.md").write_text(body, encoding="utf-8")
    return str(wd)


if __name__ == "__main__":
    import json
    import sys
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd == "resolve":
        print(json.dumps(resolve(sys.argv[2] if len(sys.argv) > 2 else ""), indent=2))
    elif cmd == "preamble":
        # Print the role text for a persona id (used by tooling/tests).
        print(persona_preamble(sys.argv[2] if len(sys.argv) > 2 else ""))
    elif cmd == "seed":
        # seed <room> <agent> <persona> -> writes context files, prints workdir.
        room = sys.argv[2] if len(sys.argv) > 2 else "discovery"
        agent = sys.argv[3] if len(sys.argv) > 3 else ""
        persona = sys.argv[4] if len(sys.argv) > 4 else ""
        print(seed_agent_context(room, agent, persona))
    else:
        print(json.dumps(list_personas(), indent=2))
